version: "3"
services:
    game-engine:
        image: coderone.azurecr.io/bomberland-engine:2381
        volumes:
            - type: "bind"
              source: ./agents/replay.json
              target: /app/replay.json

    go-agent:
        build:
            context: agents/go
            dockerfile: Dockerfile

    agent:
        build:
            context: agents/python3
            dockerfile: Dockerfile

    agent-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./agents/python3:/app

    random-agent:
        build:
            context: python3
            dockerfile: Dockerfile.random

    rule-agent:
        build:
            context: python3
            dockerfile: Dockerfile.rule

    nn-agent:
        build:
            context: python3
            dockerfile: Dockerfile.nn

    rule-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.rule.dev
        volumes:
            - ./python3:/app

    python3-fwd:
        build:
            context: agents/python3
            dockerfile: Dockerfile.fwd

    python3-fwd-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.fwd.dev
        volumes:
            - ./agents/python3:/app
    python3-gym-dev:
        build:
            context: agents/python3
            dockerfile: Dockerfile.gym.dev
        volumes:
            - ./agents/python3:/app

    typescript-agent:
        build:
            context: agents/typescript
            dockerfile: Dockerfile

    typescript-agent-dev:
        build:
            context: agents/typescript
            dockerfile: Dockerfile.dev
        volumes:
            - ./agents/typescript:/app

    cpp-agent:
        build:
            context: agents/cpp
            dockerfile: Dockerfile

    rust-agent:
        build:
            context: agents/rust
            dockerfile: Dockerfile

    published-agent:
        image: docker.io/opryzhek/bombermann:good-search-2

    il-agent:
        image: docker.io/opryzhek/bombermann:il-1

    enemy-agent:
        image: public.docker.cloudgamepad.com/gocoder/f439u384k4554etg-baseline
