version: "3.2"
services:
    game-engine:
        image: coderone.azurecr.io/bomberland-engine:2381
        volumes:
              - type: "bind"
                source: ./agents/replay.json
                target: /app/replay.json
        ports:
            - {{PORT}}:3000
        environment:
            - ADMIN_ROLE_ENABLED=1
            - AGENT_ID_MAPPING=agentA,agentB
            - INITIAL_HP=3
            - PRNG_SEED=1234
            - SHUTDOWN_ON_GAME_END_ENABLED=1
            - TELEMETRY_ENABLED=1
            - TICK_RATE_HZ=10
            - TRAINING_MODE_ENABLED=0
            # - WORLD_SEED=1348
            - GAME_START_DELAY_MS=500
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1024M"
        networks:
            - coderone-tournament

    agent-a:
        image: docker.io/opryzhek/bombermann:newrule3
        environment:
            - GAME_CONNECTION_STRING=ws://game-engine:3000/?role=agent&agentId=agentA&name=empty-agent-dev
        depends_on:
            - game-engine
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1024M"
        networks:
            - coderone-tournament

    agent-b:
        build:
            context: ../../../space_competition
            dockerfile: Dockerfile.rule.dev
        volumes:
            - ../../../space_competition:/app
        environment:
            - GAME_CONNECTION_STRING=ws://game-engine:3000/?role=agent&agentId=agentB&name=space_competition-agent
        depends_on:
            - game-engine
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: "1024M"
        networks:
            - coderone-tournament
        restart: on-failure

networks:
    coderone-tournament:
