search_budget_big = 50
search_budget_small = 25
search_horizon = 30
endgame_fire_start_danger = 3.0
endgame_fire_end_danger = 0.0  # danger of the endgame fire in the center
endgame_fire_base_multiplier = 0.1
endgame_fire_else = 40
endgame_fire_endgame_multiplier_per_fire = 0.02
endgame_fire_center_discount_mass = -0.2
endgame_fire_center_discount = -0.2  # gets multiplied by HP.
my_bomb_starting_danger = 15
enemy_bomb_starting_danger = 500
enemy_potential_bomb_danger = 100
bomb_end_danger_ticks = 5
unarmed_bomb_danger_modifier_enemy = 1 / search_horizon - 0.0001
unarmed_bomb_danger_modifier_my = 0.9
bomb_end_danger_max = 550
close_cell_danger = 0.1
bomb_arming_ticks = 5
power_up_discount = -0.5
close_enemy_discount = -0.2
close_to_center_enemy_discount = -2
center_occupied_ammo_discount = 0.1
enemy_in_danger_discount = -0.1
enemy_in_danger_one_cell_discount = -0.5
move_on_occupied_spot_penalty = my_bomb_starting_danger - 1
explosion_danger = 100000
stand_on_bomb_danger = 999
enclosed_bomb_danger = stand_on_bomb_danger + 5  # shouldn't move to occupied spot
possibly_enclosed_bomb_danger = stand_on_bomb_danger - 5
close_enemy_danger = 1
